name: CI

#on:
  #push:
  #  branches:
  #    - main

on: [push]

jobs:
  sast-scan:
    name: Run Bandit scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install bandit
      run: pip install bandit

    - name: Run bandit scan
      run: bandit -ll -ii -f json -o bandit-report.json -r .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-report
        path: bandit-report.json
      
  image-scan:
    name: Build image and run image scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build docker image
      run: docker build -f Dockerfile -t mayapp:latest .

    - name: Docker scout scan
      run: |
        curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
        docker scout quickview
        docker scout cves

        
